### ISSUE TITLE
Helix Display LCD

### ISSUE THREAD

**Issue by TnnsBeast** [vascofazza/8bit-cpu#8]
Could you provide the name of the LCD Display used with the Helix Display Interface? I am struggling to find one with the correct pin layout.

**Comment by vascofazza** [comment]
Hi @TnnsBeast that is just a regular 16x2 LCD display with the Hitachi driver. The pinout layout is not the most common one but that's the only thing I had laying around. 
You can find the pinout in the schematics 
<img width="399" alt="image" src="https://github.com/vascofazza/8bit-cpu/assets/1597575/1f15e080-4ea3-44cb-a8d4-d6d173518e2b">
And the display is something similar to this, at least the pinout is the same https://www.digikey.com/en/products/detail/newhaven-display-intl/NHD-0216BZ-FL-YBW/1701195.
https://newhavendisplay.com/content/specs/NHD-0216BZ-FL-YBW.pdf

The easiest thing you can do is probably build an adapter between the two pin layouts, they are exactly the same except for the arrangement. 
I just found the schematics here: https://www.cpmspectrepi.uk/raspberry_pi/MoinMoinExport/VariousDisplays.html
![image](https://github.com/vascofazza/8bit-cpu/assets/1597575/ed66de99-6249-4943-9441-a8a72d3a94a1)

**Comment by TnnsBeast** [comment]
Great, thank you!
